# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f203c4de9b9f61aee04ace81457cf14921c1a9326e07a8f4738510945bab52e9dbdf9305619d2c1a5ae2995bb65bad5e1fed865016c0bd1954abbf4e0dc1fb

test:
  secret_key_base: 744aedfa23869b82ae033859dbb2179f8acf057c409abe77af8d386fb8916f383730a8e4a519a3d334a9d2a7a1599368239789a8e43eb83e1b16381db696099c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
